### ISSUE TITLE
src file does not exist

### ISSUE THREAD

**Issue by mateuszsocko** [udima-university/ansible-jitsi-meet#15]
`TASK [systemli.jitsi_meet : Link additional prosody config] ****************************************************************************************************************
fatal: [193.107.XXXX]: FAILED! => {"changed": false, "msg": "src file does not exist, use \"force=yes\" if you really want to create the link: /etc/prosody/conf.avail/jitsi-test.tk.cfg.lua", "path": "/etc/prosody/conf.d/jitsi-test.tk.cfg.lua", "src": "/etc/prosody/conf.avail/jitsi-test.tk.cfg.lua"}
`

**Comment by mateuszsocko** [comment]
```
- name: Link additional prosody config
  file:
    src: "/etc/prosody/conf.avail/{{ jitsi_meet_server_name }}.cfg.lua"
    dest: "/etc/prosody/conf.d/{{ jitsi_meet_server_name }}.cfg.lua"
    owner: root
    group: root
    state: link
  notify: restart prosody
```


i think this is problem
