### ISSUE TITLE
Keeps reloading whenever I join the meeting

### ISSUE THREAD

**Issue by Oliver-ke** [udima-university/ansible-jitsi-meet#22]
Did a single install on an Ubuntu instance on AWS, whenever I go to the frontend `https://meet2.myclinify.com` and join a meeting it keeps reloading with error:
`react_devtools_backend.js:4026 2022-06-11T15:59:47.507Z [conference.js] <oce._onConferenceFailed>:  CONFERENCE FAILED: conference.focusDisconnected`

checking Jicofo logs I see
`org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
	at org.jivesoftware.smack.SASLAuthentication.authenticationFailed(SASLAuthentication.java:286)
	at org.jivesoftware.smack.AbstractXMPPConnection.lambda$new$2(AbstractXMPPConnection.java:407)
	at org.jivesoftware.smack.NonzaCallback$ClassAndConsumer.accept(NonzaCallback.java:177)
	at org.jivesoftware.smack.NonzaCallback$ClassAndConsumer.access$200(NonzaCallback.java:166)
	at org.jivesoftware.smack.NonzaCallback.onNonzaReceived(NonzaCallback.java:46)
	at org.jivesoftware.smack.AbstractXMPPConnection.parseAndProcessNonza(AbstractXMPPConnection.java:1447)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1700(XMPPTCPConnection.java:130)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1007)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$700(XMPPTCPConnection.java:913)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:936)
	at java.base/java.lang.Thread.run(Thread.java:829)
Jicofo 2022-06-12 03:09:44.090 INFO: [31] [xmpp_connection=client] XmppProviderImpl.doConnect#209: Connected, JID=null
Jicofo 2022-06-12 03:09:44.091 SEVERE: [31] [xmpp_connection=client] XmppProviderImpl.doConnect#228: Failed to connect/login: SASLError using SCRAM-SH`

this is my configuration
[host_vars/meet2.myclinify.com/main.yml]
``` yml
## Note
# Do not use chars other than [a-zA-Z0-9._-] for usernames
# prosody likes to encode chars other than alphanumerics in files/dirs names

# Meet
# Limit the number of videostreams to clients (-1 -> no limit)
channelLastN: -1
defaultLanguage: en

# Jicofo
jicofo_user: focus # DO NOT change this, ignored by jicofo postinst, hardcoded god knows where else
jicofo_pass: "{{ vault_jicofo_pass }}"
# Jicofo Component secret (debconf: jicofo/jicofosecret
jicofo_secret: "{{ vault_jicofo_secret }}"
```
[host_vars/mee2.myclinify.com/Osecret.ym] -> looks something like this
``` yml
## Required vars for central host
# XMPP Password for jicofo
vault_jicofo_pass: 6a47be54b869b664bad92894b414e748
# XMPP Password for jicofo component
vault_jicofo_secret: m4Cr30
# If using prometheus exporter
vault_exporter_xmpp_pass: 12dc103458cc91552c9741be89a00a53

## Optional vars (if central host also runs videobridge or jibri)
# XMPP Password for videbridge
vault_videobridge_pass: b4f8a72484dc27255cbbb849073f4010
# XMPP Password for jibri
vault_jibri_pass: 81cc0bbd94a3W8453aa90efac4359267

```

What do you think I might be doing wrong, please kindly assist.
