### ISSUE TITLE
[Multiple Node Deployment] JBV server not connecting

### ISSUE THREAD

**Issue by Oliver-ke** [udima-university/ansible-jitsi-meet#23]
Hi, I'm currently doing `Multiple node deployments`, the central server where Jicofo and the meet frontend seem to work perfectly, but adding a new `jvb` server refuses to connect. 
- users are created with the correct password.
- jvb on the central server connects appropriately.
- ports 80, 443, and UDP 1000 are open on all servers.

Screenshot of jvb.log on another server running Jvb
<img width="1440" alt="Screenshot 2022-06-16 at 10 49 58 AM" src="https://user-images.githubusercontent.com/32667315/174057027-214a1c09-10d1-4b04-831b-f5f5fb6da66b.png">

My JVB `main.yml`
``` yml
## Videobridge XMPP credetials
videobridge_user: 54.246.188.93
videobridge_pass: "{{ vault_videobridge_pass }}"
# Set this to something different that "videobridge_user" if you want to share
# videobridge_user and videobridge_pass across different videobridges
videobridge_muc_nick: 54.246.188.93
```

Please kindly assist, what could possibly be the issue? thanks as you do so
